### PR TITLE
Added production-ready Dockerfile

### PR DESCRIPTION
**Pull request by KrzysztofZawisla**
Hey, I added production-ready Dockerfile to ur project. U can add CI/CD to that to automate pushing to Docker Hub. If u want to test how it works u have to build image.

```sh
docker build . -t jwtcli
```

After that u can use it as normally installed app.

```sh
docker run jwtcli decode *token*
```

### CODE REVIEW

**Review by WojtekBuczko — APPROVED** [review]
good

**Review by losek1 — APPROVED** [review]
cool

**Review by kaurelia — APPROVED** [review]
👍

**Comment by mike-engel** [comment]
Hi @KrzysztofZawisla, thanks for this PR. At this time, however, I'm not interested in maintaining a dockerized version of this tool. I'm going to close this for now, but if I change my mind I'll re-open this later.

**Pull request closed without merging**
